platform :ios, '15.0'

use_frameworks!

# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

# If you use Swift packages alongside CocoaPods, you typically don't need use_frameworks!
# use_frameworks!

# Project name: Notelayer

# Pods for Notelayer

target 'Notelayer' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase'
  pod 'GoogleSignIn', '~> 7.0'
  pod 'GTMSessionFetcher/Core', '~> 3.4'
end

require 'fileutils'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_DISABLE_DEPENDENCY_SCAN'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end

    target.build_phases.each do |phase|
      next unless phase.respond_to?(:name) && phase.name == 'Create Symlinks to Header Folders'
      phase.output_paths ||= []
      if phase.output_paths.empty?
        phase.output_paths << '$(DERIVED_FILE_DIR)/symlink-headers-$(TARGET_NAME)'
      end
    end
  end
end

post_integrate do |installer|
  grpc_modulemap_src = File.join(installer.sandbox.root, 'Target Support Files', 'gRPC-Core', 'gRPC-Core.modulemap')
  grpc_modulemap_dst_dir = File.join(installer.sandbox.root, 'Headers', 'Private', 'grpc')
  if File.exist?(grpc_modulemap_src)
    FileUtils.mkdir_p(grpc_modulemap_dst_dir)
    grpc_modulemap_dst = File.join(grpc_modulemap_dst_dir, 'gRPC-Core.modulemap')
    unless File.exist?(grpc_modulemap_dst) && File.identical?(grpc_modulemap_src, grpc_modulemap_dst)
      FileUtils.cp(grpc_modulemap_src, grpc_modulemap_dst)
    end
  end
end

# If you need to add pods for extensions, define targets here.
# Example:
# target 'NotelayerShareExtension' do
#   # Pods for Share Extension
# end
