require "base64"
require "shellwords"

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    key_content = ENV["ASC_PRIVATE_KEY"].to_s
    # Treat non-PEM key content as base64.
    is_base64 = !key_content.include?("BEGIN")
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: key_content,
      is_key_content_base64: is_base64
    )

    key_file_content = is_base64 ? Base64.decode64(key_content) : key_content
    tmp_dir = ENV["RUNNER_TEMP"] || ENV["TMPDIR"] || "/tmp"
    key_path = File.join(tmp_dir, "AuthKey.p8")
    File.write(key_path, key_file_content)

    signing_args = [
      "-allowProvisioningUpdates",
      "-authenticationKeyPath #{Shellwords.escape(key_path)}",
      "-authenticationKeyID #{ENV["ASC_KEY_ID"]}",
      "-authenticationKeyIssuerID #{ENV["ASC_ISSUER_ID"]}"
    ].join(" ")

    run_number = ENV["GITHUB_RUN_NUMBER"]
    run_attempt = ENV["GITHUB_RUN_ATTEMPT"]
    build_number = nil

    if run_number
      build_number = run_number
      if run_attempt && run_attempt != "1"
        build_number = "#{run_number}.#{run_attempt}"
      end
    end

    if build_number
      increment_build_number(
        xcodeproj: "ios-swift/Notelayer/Notelayer.xcodeproj",
        build_number: build_number
      )
    else
      increment_build_number(
        xcodeproj: "ios-swift/Notelayer/Notelayer.xcodeproj"
      )
    end

    build_app(
      project: "ios-swift/Notelayer/Notelayer.xcodeproj",
      scheme: "Notelayer",
      export_method: "app-store",
      xcargs: signing_args,
      export_xcargs: signing_args
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end
